personal_finance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("testapp.urls")),
]

testapp/urls.py
from django.urls import path

from . import views

app_name = "testapp"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("spending/", views.AnalyticView.as_view(), name="spending"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.register_user, name="register"),
    path("ajax/post/url", views.ajax_post, name="ajax_post"),
]

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Bootstrap CSS -->
    {% load static %}
    <link rel="icon" href="{% static 'testapp/img/money.png' %}" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script defer src="{% static 'testapp/js/script.js' %}"></script>
    <script src="{% static 'testapp/js/calculate.js' %}"></script>
    <link rel="stylesheet" href="{% static 'testapp/css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'testapp/css/empty.css' %}" />
    <link rel="stylesheet" href="{% static 'testapp/css/footer.css' %}" />
    <link rel="stylesheet" href="{% static 'testapp/css/index.css' %}" />
    <link rel="stylesheet" href="{% static 'testapp/css/insights.css' %}" />
    <link rel="stylesheet" href="{% static 'testapp/css/login.css' %}" />
    <link rel="stylesheet" href="{% static 'testapp/css/signup.css' %}" />
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
      integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT"
      crossorigin="anonymous"
    ></script>
    <title>Savor</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light sticky-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'testapp:index' %}">
          <img
            src="{% static 'testapp/img/money.png' %}"
            alt=""
            class="d-inline-block align-text-top"
          />
        </a>
        <div class="burger-account">
          <div class="dropdown">
            <button class="account-toggler">
              <img
                src="{% static 'testapp/img/account.png' %}"
                alt=""
                class="d-inline-block align-text-top"
              />
              <div class="dropdown-content">
                {% if user.is_authenticated %}
                <a href="{% url 'testapp:logout' %}">Logout</a>
                {% else %}
                <a href="{% url 'testapp:index' %}">Login</a>
                <a href="{% url 'testapp:register' %}">Register</a>
                {% endif %}
              </div>
            </button>
          </div>
          <button
            class="navbar-toggler bg-light"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon bg-light"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'testapp:spending' %}"
                >Analytics</a
              >
            </li>
            {% else %} {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    {% if messages %} {% for message in messages %}
    <div class="auth-alerts">
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ message }}
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="alert"
          aria-label="Close"
        ></button>
      </div>
    </div>
    {% endfor %} {% endif %} {% block content %} {% endblock %}
  </body>
</html>